name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: GCC 4.9
            env:
              CC: gcc-4.9
              CXX: g++-4.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Boost
        run: sudo apt-get update && sudo apt-get install -yq libboost-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
